[core]
threadPoolSize = 4

[servername]
lobby = '§f§l大厅服'
survival = '§2§l生存服'
creative = '§6§l创造服'
discord = '§a§lDiscord'
kook = '§a§lKook'
qq = '§a§lQQ'

[minecraft]
completeTakeoverMode = false

[minecraft.message]
chat = '§7[{server}§7]§e{name}§r: {message}'
join = '§8[§a+§8] §7[{server}§7] §e{name}'
leave = '§8[§c-§8] §e{name}'
switch = '§8[§b❖§8] §e{name}§r: §7«{serverFrom}§7» §6➟ §7«{serverTo}§7»'
msgSender = '§7§o你悄悄地对{target}说: {message}'
msgTarget = '§7§o{sender}悄悄地对你说: {message}'
list = '§8§l» §7[{server}§7] 当前共有§6{count}§7名玩家在线: §e{playerList}'
listEmpty = '当前没有玩家在线'

[discord]
enable = false
token = ''
channelId = ''

[discord.message]
chat = '[{server}] <{name}>: {message}'
join = '[+] [{server}] {name}'
leave = '[-] {name}'
switch = '<{name}>: [{serverFrom}] ➟ [{serverTo}]'
list = '- [{server}] 当前共有{count}名玩家在线: {playerList}'
listEmpty = '当前没有玩家在线'

[discord.proxy]
enable = false
proxyHost = '127.0.0.1'
proxyPort = 1080

[kook]
enable = false
token = ''
channelId = ''

[kook.daemon]
enable = false
interval = 60
retry = 3

[kook.message]
chat = '[{server}] <{name}>: {message}'
join = '[+] [{server}] {name}'
leave = '[-] {name}'
switch = '<{name}>: [{serverFrom}] ➟ [{serverTo}]'
list = '- [{server}] 当前共有{count}名玩家在线: {playerList}'
listEmpty = '当前没有玩家在线'

[qq]
enable = false
groupId = ''

[qq.api]
host = '0.0.0.0'
wsReversePort = 9001
wsReversePath = '/ws/'

[qq.message]
chat = '[{server}] <{name}>: {message}'
join = '[+] [{server}] {name}'
leave = '[-] {name}'
switch = '<{name}>: [{serverFrom}] ➟ [{serverTo}]'
list = '- [{server}] 当前共有{count}名玩家在线: {playerList}'
listEmpty = '当前没有玩家在线'
